algoritmo "Beijus"
var
  coco: real
  beiju: inteiro
  goma: real
  massa: real
inicio
   Escreval ("Bem-vindo")
   Escreval ("Aqui você verá a quantidade necessária de ingredientes para fazer os beijus")
   coco <- 10.5
   goma <- 13
   massa <- 13
   beiju <- 42
   Escreval ("Para fazer ", beiju, " peças de beiju, você precisará de", goma, "kg de goma,")
   Escreval (massa, "kg de massa e ", coco, "kg de coco ralado.")
fimalgoritmo
