algoritmo "semnome"
// Função :
// Autor :
// Data : 05/06/2024
// Seção de Declarações 
var
   a, b: real
inicio
   Escreva ("Escreva um valor para A: ")
   leia (a)
   Escreva ("Escreva um valor para B: ")
   leia (b)
   Escreval ("Adição: ", a + b)
   Escreval ("Subtração: ", a - b)
   Escreval ("Multiplicação: ", a*b)
   Escreval ("Divisão: ", a/b)
   Escreval ("Divisão Inteira: ", a\b)
   Escreval ("Exponenciação: ", a^b)
   Escreval ("Módulo: ", a % b)
fimalgoritmo
